tags:

paths:
  #LOGIN
  /auth/login:
    post:
      tags:
        - authentication
      summary: Login
      description: Login
      operationId: login
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Login
          required: true
          schema:
            type: object
            required:
              - phone
              - password
            properties:
              phone:
                type: string
                description: user phone
              password:
                type: string
                description: user Password
      responses:
        "200":
          description: Login
          schema:
            $ref: "#/definitions/authentication"
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error

  #LOGOUT
  /auth/logout:
    get:
      tags:
        - authentication
      summary: Logout
      security:
        - bearerAuth: []
      description: Logout
      operationId: logout
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: Logout
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error

  /users:
    # REGISTER
    post:
      tags:
        - users
      summary: Register
      description: Register
      operationId: register
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Register
          required: true
          schema:
            type: object
            required:
              - email
              - password
            properties:
              phone:
                type: string
                description: user Email
              password:
                type: string
                description: user Password
      responses:
        "200":
          description: Register
          schema:
            $ref: "#/definitions/users"
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error

    # UPDATE
    put:
      tags:
        - users
      summary: Update
      security:
        - bearerAuth: []
      description: Update
      operationId: update
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Update
          required: true
          schema:
            type: object
            $ref: "#/definitions/users"
      responses:
        "200":
          description: Update
          schema:
            $ref: "#/definitions/users"
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error

  # CHANGE PASSWORD
  /users/change-password:
    put:
      tags:
        - users
      summary: Change password
      security:
        - bearerAuth: []
      description: Change password
      operationId: Change password
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        in: body
        name: body
        description: Change password
        required: true
        schema:
          type: object
          required:
            - password
          properties:
            password:
              type: string
              description: user New Password
      responses:
        "200":
          description: Change password
          schema:
            $ref: "#/definitions/users"
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error

  #PRODUCTS
  /products:
    # GET LIST PRODUCTS
    get:
      tags:
        - products
      summary: Get products
      security:
        - bearerAuth: []
      description: Get products
      operationId: getProducts
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: Get products
          schema:
            type: array
            items:
              type: object
              $ref: "#/definitions/products"
        "500":
          description: Internal Server Error
    #CREATE PRODUCT
    post:
      tags:
        - products
      summary: Create product
      security:
        - bearerAuth: []
      description: Create product
      operationId: createProduct
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Create product
          required: true
          schema:
            type: object
            required:
              - name
              - price
              - img
              - description
            properties:
              name:
                type: string
                description: product Name
              price:
                type: integer
                description: product Price
              img:
                type: string
                description: product Image
              description:
                type: string
                description: product Description
      responses:
        "200":
          description: Create product
          schema:
            $ref: "#/definitions/products"
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error

  #BILL
  /bills:
    #create bill
    post:
      tags:
        - bills
      summary: Create bill
      security:
        - bearerAuth: []
      description: Create bill
      operationId: createBill
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Create bill
          required: true
          schema:
            type: object
            required:
              - items
            properties:
              items:
                type: array
                items:
                  type: object
                  required:
                    - product
                    - quantity
                  properties:
                    product:
                      type: string
                      description: product ID
                    quantity:
                      type: integer
                      description: product Quantity
      responses:
        "200":
          description: Create bill
          schema:
            type: object
            required:
              - id
              - items
              - total
              - status
            properties:
              id:
                type: string
                description: bill ID
              items:
                type: array
                items:
                  type: object
                  required:
                    - productId
                    - quantity
                  properties:
                    id:
                      type: string
                      description: product ID
                    quantity:
                      type: integer
                      description: product Quantity
              total:
                type: integer
                description: bill Total
              status:
                type: string
                description: bill Status
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
        "400":
          description: Bad Request

    #GET MY LIST BILL
    get:
      tags:
        - bills
      summary: Get my list bill
      security:
        - bearerAuth: []
      description: Get my list bill
      operationId: getMyListBill
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: Get my list bill
          schema:
            type: array
            items:
              type: object
              required:
                - id
                - items
                - total
                - status
              properties:
                id:
                  type: string
                  description: bill ID
                items:
                  type: array
                  items:
                    type: object
                    required:
                      - id
                      - quantity
                    properties:
                      id:
                        type: string
                        description: product ID
                      quantity:
                        type: integer
                        description: product Quantity
                total:
                  type: integer
                  description: bill Total
                status:
                  type: string
                  description: bill Status
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error

    #GET BILL BY ID
  /bills/{id}:
    get:
      tags:
        - bills
      summary: Get bill by id
      security:
        - bearerAuth: []
      description: Get bill by id
      operationId: getBillById
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          description: bill ID
          required: true
          type: string
      responses:
        "200":
          description: Get bill by id
          schema:
            type: object
            required:
              - id
              - items
              - total
              - status
            properties:
              id:
                type: string
                description: bill ID
              items:
                type: array
                items:
                  type: object
                  required:
                    - id
                    - quantity
                  properties:
                    id:
                      type: string
                      description: product ID
                    quantity:
                      type: integer
                      description: product Quantity
              total:
                type: integer
                description: bill Total
              status:
                type: string
                description: bill Status
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error

definitions:
  users:
    type: object
    required: -email
      -name
      -address
      -phone
      -dob
      -avatar
      -id
    properties:
      phone:
        type: string
        description: user Phone number
      name:
        type: string
        description: user Name
      address:
        type: string
        description: user Address
      dob:
        type: string
        description: user Date of Birth
      avatar:
        type: string
        description: user Avatar
      id:
        type: string
        description: user ID

  authentication:
    type: object
    required: -token
      -user
    properties:
      token:
        type: string
        description: token
      user:
        type: object
        description: user
        $ref: "#/definitions/users"

  products:
    type: object
    required: -id
      -name
      -price
      -image
      -description
    properties:
      id:
        type: string
        description: product ID
      name:
        type: string
        description: product Name
      price:
        type: integer
        description: product Price
      image:
        type: string
        description: product Image
      description:
        type: string
        description: product Description
